package com.company.learninghub.communication.domain;

public enum CommunicationEventType {
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_BY_ADMIN,
    ACCOUNT_CREATED,
    ACCOUNT_ACTIVATED,
    ACCOUNT_DEACTIVATED,
    CERTIFICATE_SUBMITTED,
    CERTIFICATE_APPROVED,
    CERTIFICATE_REJECTED,
    LEARNING_STAGE_COMPLETED,
    LEARNING_ROADMAP_COMPLETED,
    CONTINUE_LEARNING_REMINDER,
    PROJECT_MEMBER_ADDED,
    PROJECT_REPOSITORY_ADDED,
    PROJECT_ENVIRONMENT_ADDED
}
